set nocompatible
filetype off
set rtp+=~/.vimplugins/Vundle.vim
call vundle#begin("~/.vimplugins")
Plugin 'gmarik/Vundle.vim'

Plugin 'easymotion/vim-easymotion'
Plugin 'tpope/vim-surround'

Plugin 'sirtaj/vim-openscad'
Plugin 'JuliaLang/julia-vim'

Plugin 'altercation/vim-colors-solarized' 
Plugin 'kien/rainbow_parentheses.vim' 

Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'

call vundle#end()
filetype plugin indent on

set number	

"nerdtree
map <C-n> :NERDTreeToggle<CR>

autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif "close if only nerdtree is open
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "M",
    \ "Staged"    : "+",
    \ "Untracked" : "?",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "¤",
    \ "Deleted"   : "-",
    \ "Dirty"     : "!",
    \ "Clean"     : "✔︎",
    \ "Unknown"   : "?"
    \ }
"syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_auto_jump = 3


" wrapping
" http://blog.ezyang.com/2010/03/vim-textwidth/
set linebreak
set textwidth=79
set formatoptions=cq
set wrapmargin=0
set colorcolumn=+1
"

set showmatch	
	
set errorbells	
set visualbell	
 
set hlsearch	
set smartcase	
set ignorecase	
set incsearch	
 
set autoindent	
set cindent	
set expandtab	
set shiftwidth=2	
set smartindent	
set smarttab	
set softtabstop=4	

set clipboard=unnamedplus

set ruler	
 
set undolevels=1000	
set backspace=indent,eol,start	

"theme

syntax enable
set cursorline
let g:solarized_termtrans = 1
set background=dark
colorscheme solarized

"parentheses coloring

let g:rbpt_colorpairs = [
    \ ['gray',        'RoyalBlue3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ]

let g:rbpt_max = 8

au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

"bindings

"""""
"https://gist.github.com/AndrewRadev/1171559

onoremap an :<c-u>call <SID>NextTextObject('a')<cr>
xnoremap an :<c-u>call <SID>NextTextObject('a')<cr>
onoremap in :<c-u>call <SID>NextTextObject('i')<cr>
xnoremap in :<c-u>call <SID>NextTextObject('i')<cr>

function! s:NextTextObject(motion)
    echo
    let c = nr2char(getchar())
    exe "normal! f".c."v".a:motion.c
endfunction
"""""


let g:EasyMotion_do_mapping = 0

let g:EasyMotion_keys = 'qwertasdfxcgtvbnhypm1234567890uiojkl'

let g:EasyMotion_re_anywhere = '\v(<.|^)'



nmap q <plug>(easymotion-jumptoanywhere)


