#!/bin/bash

#http://minimul.com/increased-developer-productivity-with-tmux-part-4.html

SESSION=`basename $PWD`

tmux rename-window -t 0 $SESSION
tmux split-window -h
tmux select-pane -t 0
tmux resize-pane -x 90

tmux select-pane -t 1
tmux split-window -v
tmux select-pane -t 1
tmux resize-pane -y 10
tmux send-keys 'watchgit' Enter

tmux select-pane -t 0

