#!/bin/sh

#https://exyr.org/2011/inotify-run/

clear

FORMAT=$(echo -e "\033[1;33m%w%f\033[0m written")
git status -sb
while inotifywait -qre close_write --format "$FORMAT" .
do
    git status -sb
done
