#!/bin/sh

#https://exyr.org/2011/inotify-run/

clear

FORMAT=$(echo -e "\033[1;33m%w%f\033[0m written")

python -m unittest discover -fq
while inotifywait -qre close_write --format "$FORMAT" .
do
    clear
    python -m unittest discover -fq|head
done
